name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test application
        run: |
          python -m py_compile app.py

      - name: Build Docker image
        run: |
          docker build -t cicd-flask-app .

      - name: Run Docker container
        run: |
          docker run -d -p 5000:5000 --name cicd-container cicd-flask-app

      - name: Check application
        run: |
          sleep 5
          curl http://localhost:5000